import type { SceneData } from '../types';

export const demoScenes: Record<string, SceneData> = {
  office: {
    version: '1.0.0',
    objects: [
      { id: 'office-desk-1', name: '桌子_1', kind: 'table', position: { x: -2, y: 0, z: 0 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1.5, y: 1, z: 1 }, color: '#8B7355', visible: true, locked: false, occlusionIndex: 0 },
      { id: 'office-desk-2', name: '桌子_2', kind: 'table', position: { x: 2, y: 0, z: 0 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1.5, y: 1, z: 1 }, color: '#8B7355', visible: true, locked: false, occlusionIndex: 1 },
      { id: 'office-desk-3', name: '桌子_3', kind: 'table', position: { x: -2, y: 0, z: -3 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1.5, y: 1, z: 1 }, color: '#8B7355', visible: true, locked: false, occlusionIndex: 2 },
      { id: 'office-desk-4', name: '桌子_4', kind: 'table', position: { x: 2, y: 0, z: -3 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1.5, y: 1, z: 1 }, color: '#8B7355', visible: true, locked: false, occlusionIndex: 3 },
      { id: 'office-chair-1', name: '椅子_1', kind: 'chair', position: { x: -2, y: 0, z: 1 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1, y: 1, z: 1 }, color: '#4A4A4A', visible: true, locked: false, occlusionIndex: 4 },
      { id: 'office-chair-2', name: '椅子_2', kind: 'chair', position: { x: 2, y: 0, z: 1 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1, y: 1, z: 1 }, color: '#4A4A4A', visible: true, locked: false, occlusionIndex: 5 },
      { id: 'office-chair-3', name: '椅子_3', kind: 'chair', position: { x: -2, y: 0, z: -2 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1, y: 1, z: 1 }, color: '#4A4A4A', visible: true, locked: false, occlusionIndex: 6 },
      { id: 'office-chair-4', name: '椅子_4', kind: 'chair', position: { x: 2, y: 0, z: -2 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1, y: 1, z: 1 }, color: '#4A4A4A', visible: true, locked: false, occlusionIndex: 7 },
      { id: 'office-cup-1', name: '杯子_1', kind: 'cup', position: { x: -1.5, y: 1, z: 0.3 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 0.5, y: 0.5, z: 0.5 }, color: '#FFFFFF', visible: true, locked: false, occlusionIndex: 8 },
      { id: 'office-cup-2', name: '杯子_2', kind: 'cup', position: { x: 2.5, y: 1, z: 0.3 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 0.5, y: 0.5, z: 0.5 }, color: '#FF6B6B', visible: true, locked: false, occlusionIndex: 9 },
      { id: 'office-person-1', name: '人物_1', kind: 'person', position: { x: 0, y: 0, z: 2 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1, y: 1, z: 1 }, color: '#4A90D9', visible: true, locked: false, occlusionIndex: 10 },
      { id: 'office-person-2', name: '人物_2', kind: 'person', position: { x: 0, y: 0, z: -4 }, rotation: { x: 0, y: Math.PI, z: 0 }, scale: { x: 1, y: 1, z: 1 }, color: '#E85D75', visible: true, locked: false, occlusionIndex: 11 },
      { id: 'office-partition-1', name: '隔断_1', kind: 'box', position: { x: -4, y: 1, z: -1.5 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 0.2, y: 2, z: 3 }, color: '#D4C5B9', visible: true, locked: false, occlusionIndex: 12 },
      { id: 'office-partition-2', name: '隔断_2', kind: 'box', position: { x: 4, y: 1, z: -1.5 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 0.2, y: 2, z: 3 }, color: '#D4C5B9', visible: true, locked: false, occlusionIndex: 13 },
    ],
    metadata: { name: '办公室', createdAt: '', updatedAt: '' },
  },
  living_room: {
    version: '1.0.0',
    objects: [
      { id: 'lr-sofa-1', name: '沙发_1', kind: 'sofa', position: { x: 0, y: 0, z: 3 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 2.5, y: 1, z: 1 }, color: '#6B8E7B', visible: true, locked: false, occlusionIndex: 0 },
      { id: 'lr-table-1', name: '桌子_1', kind: 'table', position: { x: 0, y: 0, z: 1.5 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1.2, y: 0.8, z: 0.8 }, color: '#8B7355', visible: true, locked: false, occlusionIndex: 1 },
      { id: 'lr-chair-1', name: '椅子_1', kind: 'chair', position: { x: -1, y: 0, z: 0.5 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1, y: 1, z: 1 }, color: '#4A4A4A', visible: true, locked: false, occlusionIndex: 2 },
      { id: 'lr-chair-2', name: '椅子_2', kind: 'chair', position: { x: 1, y: 0, z: 0.5 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1, y: 1, z: 1 }, color: '#4A4A4A', visible: true, locked: false, occlusionIndex: 3 },
      { id: 'lr-cabinet-1', name: '柜子_1', kind: 'box', position: { x: -3, y: 0.8, z: -2 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1, y: 1.5, z: 0.6 }, color: '#C4A882', visible: true, locked: false, occlusionIndex: 4 },
      { id: 'lr-cabinet-2', name: '柜子_2', kind: 'box', position: { x: 3, y: 0.8, z: -2 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1, y: 1.5, z: 0.6 }, color: '#C4A882', visible: true, locked: false, occlusionIndex: 5 },
    ],
    metadata: { name: '客厅', createdAt: '', updatedAt: '' },
  },
  street: {
    version: '1.0.0',
    objects: [
      { id: 'st-house-1', name: '房子_1', kind: 'house', position: { x: -5, y: 0, z: 2 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 2, y: 2, z: 2 }, color: '#E8D5B7', visible: true, locked: false, occlusionIndex: 0 },
      { id: 'st-house-2', name: '房子_2', kind: 'house', position: { x: 5, y: 0, z: 2 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 2, y: 2, z: 2 }, color: '#D4C5B9', visible: true, locked: false, occlusionIndex: 1 },
      { id: 'st-car-1', name: '汽车_1', kind: 'car', position: { x: -2, y: 0, z: -2 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1.5, y: 1, z: 1 }, color: '#E85D75', visible: true, locked: false, occlusionIndex: 2 },
      { id: 'st-car-2', name: '汽车_2', kind: 'car', position: { x: 3, y: 0, z: -3 }, rotation: { x: 0, y: 0.5, z: 0 }, scale: { x: 1.5, y: 1, z: 1 }, color: '#4A90D9', visible: true, locked: false, occlusionIndex: 3 },
      { id: 'st-tree-1', name: '树木_1', kind: 'tree', position: { x: -7, y: 0, z: 0 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1, y: 1, z: 1 }, color: '#2D5A27', visible: true, locked: false, occlusionIndex: 4 },
      { id: 'st-tree-2', name: '树木_2', kind: 'tree', position: { x: 7, y: 0, z: 0 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1, y: 1, z: 1 }, color: '#2D5A27', visible: true, locked: false, occlusionIndex: 5 },
      { id: 'st-tree-3', name: '树木_3', kind: 'tree', position: { x: -7, y: 0, z: 4 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1.2, y: 1.2, z: 1.2 }, color: '#3A7A33', visible: true, locked: false, occlusionIndex: 6 },
      { id: 'st-tree-4', name: '树木_4', kind: 'tree', position: { x: 7, y: 0, z: 4 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1.2, y: 1.2, z: 1.2 }, color: '#3A7A33', visible: true, locked: false, occlusionIndex: 7 },
      { id: 'st-fence-1', name: '栅栏_1', kind: 'fence', position: { x: -6, y: 0, z: -4 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 2, y: 1, z: 1 }, color: '#8B7355', visible: true, locked: false, occlusionIndex: 8 },
      { id: 'st-fence-2', name: '栅栏_2', kind: 'fence', position: { x: -2, y: 0, z: -4 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 2, y: 1, z: 1 }, color: '#8B7355', visible: true, locked: false, occlusionIndex: 9 },
      { id: 'st-fence-3', name: '栅栏_3', kind: 'fence', position: { x: 2, y: 0, z: -4 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 2, y: 1, z: 1 }, color: '#8B7355', visible: true, locked: false, occlusionIndex: 10 },
      { id: 'st-fence-4', name: '栅栏_4', kind: 'fence', position: { x: 6, y: 0, z: -4 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 2, y: 1, z: 1 }, color: '#8B7355', visible: true, locked: false, occlusionIndex: 11 },
      { id: 'st-person-1', name: '人物_1', kind: 'person', position: { x: 0, y: 0, z: -1 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1, y: 1, z: 1 }, color: '#4A90D9', visible: true, locked: false, occlusionIndex: 12 },
    ],
    metadata: { name: '街道', createdAt: '', updatedAt: '' },
  },
  bedroom: {
    version: '1.0.0',
    objects: [
      { id: 'bd-bed-1', name: '床_1', kind: 'bed', position: { x: 0, y: 0, z: 2 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 2, y: 1, z: 1.5 }, color: '#F5F0E8', visible: true, locked: false, occlusionIndex: 0 },
      { id: 'bd-cabinet-1', name: '柜子_1', kind: 'box', position: { x: -3, y: 1, z: -2 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1.2, y: 2, z: 0.8 }, color: '#C4A882', visible: true, locked: false, occlusionIndex: 1 },
      { id: 'bd-cabinet-2', name: '柜子_2', kind: 'box', position: { x: 3, y: 1, z: -2 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1.2, y: 2, z: 0.8 }, color: '#C4A882', visible: true, locked: false, occlusionIndex: 2 },
      { id: 'bd-chair-1', name: '椅子_1', kind: 'chair', position: { x: 0, y: 0, z: -2 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1, y: 1, z: 1 }, color: '#4A4A4A', visible: true, locked: false, occlusionIndex: 3 },
      { id: 'bd-table-1', name: '桌子_1', kind: 'table', position: { x: 0, y: 0, z: -1 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1, y: 0.8, z: 0.6 }, color: '#8B7355', visible: true, locked: false, occlusionIndex: 4 },
    ],
    metadata: { name: '卧室', createdAt: '', updatedAt: '' },
  },
  park: {
    version: '1.0.0',
    objects: [
      { id: 'pk-tree-1', name: '树木_1', kind: 'tree', position: { x: -6, y: 0, z: -3 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1.5, y: 1.5, z: 1.5 }, color: '#2D5A27', visible: true, locked: false, occlusionIndex: 0 },
      { id: 'pk-tree-2', name: '树木_2', kind: 'tree', position: { x: -6, y: 0, z: 3 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1.2, y: 1.2, z: 1.2 }, color: '#3A7A33', visible: true, locked: false, occlusionIndex: 1 },
      { id: 'pk-tree-3', name: '树木_3', kind: 'tree', position: { x: 6, y: 0, z: -3 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1.5, y: 1.5, z: 1.5 }, color: '#2D5A27', visible: true, locked: false, occlusionIndex: 2 },
      { id: 'pk-tree-4', name: '树木_4', kind: 'tree', position: { x: 6, y: 0, z: 3 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1.2, y: 1.2, z: 1.2 }, color: '#3A7A33', visible: true, locked: false, occlusionIndex: 3 },
      { id: 'pk-tree-5', name: '树木_5', kind: 'tree', position: { x: 0, y: 0, z: -6 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1.3, y: 1.3, z: 1.3 }, color: '#4A8A44', visible: true, locked: false, occlusionIndex: 4 },
      { id: 'pk-tree-6', name: '树木_6', kind: 'tree', position: { x: 0, y: 0, z: 6 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1.3, y: 1.3, z: 1.3 }, color: '#4A8A44', visible: true, locked: false, occlusionIndex: 5 },
      { id: 'pk-fence-1', name: '栅栏_1', kind: 'fence', position: { x: -8, y: 0, z: 0 }, rotation: { x: 0, y: Math.PI / 2, z: 0 }, scale: { x: 3, y: 1, z: 1 }, color: '#8B7355', visible: true, locked: false, occlusionIndex: 6 },
      { id: 'pk-fence-2', name: '栅栏_2', kind: 'fence', position: { x: -5, y: 0, z: 5 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 2, y: 1, z: 1 }, color: '#8B7355', visible: true, locked: false, occlusionIndex: 7 },
      { id: 'pk-fence-3', name: '栅栏_3', kind: 'fence', position: { x: -5, y: 0, z: -5 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 2, y: 1, z: 1 }, color: '#8B7355', visible: true, locked: false, occlusionIndex: 8 },
      { id: 'pk-fence-4', name: '栅栏_4', kind: 'fence', position: { x: 5, y: 0, z: 5 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 2, y: 1, z: 1 }, color: '#8B7355', visible: true, locked: false, occlusionIndex: 9 },
      { id: 'pk-fence-5', name: '栅栏_5', kind: 'fence', position: { x: 5, y: 0, z: -5 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 2, y: 1, z: 1 }, color: '#8B7355', visible: true, locked: false, occlusionIndex: 10 },
      { id: 'pk-fence-6', name: '栅栏_6', kind: 'fence', position: { x: 8, y: 0, z: 0 }, rotation: { x: 0, y: Math.PI / 2, z: 0 }, scale: { x: 3, y: 1, z: 1 }, color: '#8B7355', visible: true, locked: false, occlusionIndex: 11 },
      { id: 'pk-fence-7', name: '栅栏_7', kind: 'fence', position: { x: -2, y: 0, z: -7 }, rotation: { x: 0, y: Math.PI / 2, z: 0 }, scale: { x: 2, y: 1, z: 1 }, color: '#8B7355', visible: true, locked: false, occlusionIndex: 12 },
      { id: 'pk-fence-8', name: '栅栏_8', kind: 'fence', position: { x: 2, y: 0, z: 7 }, rotation: { x: 0, y: Math.PI / 2, z: 0 }, scale: { x: 2, y: 1, z: 1 }, color: '#8B7355', visible: true, locked: false, occlusionIndex: 13 },
      { id: 'pk-person-1', name: '人物_1', kind: 'person', position: { x: -3, y: 0, z: -2 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1, y: 1, z: 1 }, color: '#4A90D9', visible: true, locked: false, occlusionIndex: 14 },
      { id: 'pk-person-2', name: '人物_2', kind: 'person', position: { x: 3, y: 0, z: 2 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1, y: 1, z: 1 }, color: '#E85D75', visible: true, locked: false, occlusionIndex: 15 },
      { id: 'pk-chair-1', name: '椅子_1', kind: 'chair', position: { x: -2, y: 0, z: -4 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1, y: 1, z: 1 }, color: '#6B8E7B', visible: true, locked: false, occlusionIndex: 16 },
      { id: 'pk-chair-2', name: '椅子_2', kind: 'chair', position: { x: 0, y: 0, z: -4 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1, y: 1, z: 1 }, color: '#6B8E7B', visible: true, locked: false, occlusionIndex: 17 },
      { id: 'pk-chair-3', name: '椅子_3', kind: 'chair', position: { x: 2, y: 0, z: -4 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1, y: 1, z: 1 }, color: '#6B8E7B', visible: true, locked: false, occlusionIndex: 18 },
    ],
    metadata: { name: '公园', createdAt: '', updatedAt: '' },
  },
  restaurant: {
    version: '1.0.0',
    objects: [
      { id: 'rt-table-1', name: '桌子_1', kind: 'table', position: { x: -3, y: 0, z: -2 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1.2, y: 1, z: 1.2 }, color: '#8B7355', visible: true, locked: false, occlusionIndex: 0 },
      { id: 'rt-table-2', name: '桌子_2', kind: 'table', position: { x: 3, y: 0, z: -2 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1.2, y: 1, z: 1.2 }, color: '#8B7355', visible: true, locked: false, occlusionIndex: 1 },
      { id: 'rt-table-3', name: '桌子_3', kind: 'table', position: { x: -3, y: 0, z: 2 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1.2, y: 1, z: 1.2 }, color: '#8B7355', visible: true, locked: false, occlusionIndex: 2 },
      { id: 'rt-table-4', name: '桌子_4', kind: 'table', position: { x: 3, y: 0, z: 2 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1.2, y: 1, z: 1.2 }, color: '#8B7355', visible: true, locked: false, occlusionIndex: 3 },
      { id: 'rt-chair-1', name: '椅子_1', kind: 'chair', position: { x: -3, y: 0, z: -1 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1, y: 1, z: 1 }, color: '#4A4A4A', visible: true, locked: false, occlusionIndex: 4 },
      { id: 'rt-chair-2', name: '椅子_2', kind: 'chair', position: { x: -3, y: 0, z: -3 }, rotation: { x: 0, y: Math.PI, z: 0 }, scale: { x: 1, y: 1, z: 1 }, color: '#4A4A4A', visible: true, locked: false, occlusionIndex: 5 },
      { id: 'rt-chair-3', name: '椅子_3', kind: 'chair', position: { x: 3, y: 0, z: -1 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1, y: 1, z: 1 }, color: '#4A4A4A', visible: true, locked: false, occlusionIndex: 6 },
      { id: 'rt-chair-4', name: '椅子_4', kind: 'chair', position: { x: 3, y: 0, z: -3 }, rotation: { x: 0, y: Math.PI, z: 0 }, scale: { x: 1, y: 1, z: 1 }, color: '#4A4A4A', visible: true, locked: false, occlusionIndex: 7 },
      { id: 'rt-chair-5', name: '椅子_5', kind: 'chair', position: { x: -3, y: 0, z: 1 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1, y: 1, z: 1 }, color: '#4A4A4A', visible: true, locked: false, occlusionIndex: 8 },
      { id: 'rt-chair-6', name: '椅子_6', kind: 'chair', position: { x: -3, y: 0, z: 3 }, rotation: { x: 0, y: Math.PI, z: 0 }, scale: { x: 1, y: 1, z: 1 }, color: '#4A4A4A', visible: true, locked: false, occlusionIndex: 9 },
      { id: 'rt-chair-7', name: '椅子_7', kind: 'chair', position: { x: 3, y: 0, z: 1 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1, y: 1, z: 1 }, color: '#4A4A4A', visible: true, locked: false, occlusionIndex: 10 },
      { id: 'rt-chair-8', name: '椅子_8', kind: 'chair', position: { x: 3, y: 0, z: 3 }, rotation: { x: 0, y: Math.PI, z: 0 }, scale: { x: 1, y: 1, z: 1 }, color: '#4A4A4A', visible: true, locked: false, occlusionIndex: 11 },
      { id: 'rt-cup-1', name: '杯子_1', kind: 'cup', position: { x: -3, y: 1, z: -2 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 0.4, y: 0.4, z: 0.4 }, color: '#FFFFFF', visible: true, locked: false, occlusionIndex: 12 },
      { id: 'rt-cup-2', name: '杯子_2', kind: 'cup', position: { x: 3, y: 1, z: -2 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 0.4, y: 0.4, z: 0.4 }, color: '#FF6B6B', visible: true, locked: false, occlusionIndex: 13 },
      { id: 'rt-cup-3', name: '杯子_3', kind: 'cup', position: { x: -3, y: 1, z: 2 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 0.4, y: 0.4, z: 0.4 }, color: '#4A90D9', visible: true, locked: false, occlusionIndex: 14 },
      { id: 'rt-cup-4', name: '杯子_4', kind: 'cup', position: { x: 3, y: 1, z: 2 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 0.4, y: 0.4, z: 0.4 }, color: '#FFD93D', visible: true, locked: false, occlusionIndex: 15 },
      { id: 'rt-person-1', name: '人物_1', kind: 'person', position: { x: -5, y: 0, z: -2 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1, y: 1, z: 1 }, color: '#4A90D9', visible: true, locked: false, occlusionIndex: 16 },
      { id: 'rt-person-2', name: '人物_2', kind: 'person', position: { x: 5, y: 0, z: 2 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1, y: 1, z: 1 }, color: '#E85D75', visible: true, locked: false, occlusionIndex: 17 },
      { id: 'rt-person-3', name: '人物_3', kind: 'person', position: { x: 0, y: 0, z: 4 }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: 1, y: 1, z: 1 }, color: '#50C878', visible: true, locked: false, occlusionIndex: 18 },
    ],
    metadata: { name: '餐厅', createdAt: '', updatedAt: '' },
  },
};